### ISSUE TITLE
Segfault when running `examples/webrtc`

### ISSUE THREAD

**Issue by Sean-Der** [pion/mediadevices#426]
```
goroutine 1 [running]:
github.com/pion/mediadevices.(*rtpReadCloserImpl).Controller(0xc0001b24a0?)
	/Users/duboisea/go/src/github.com/pion/mediadevices/rtpreader.go:29 +0x16
github.com/pion/mediadevices.(*baseTrack).bind(0xc00007eba0, {{0xc00002ef30, 0x20}, {{0x49a2398, 0x0, 0x0}, {0xc00007ec60, 0x1, 0x1}}, 0x3b106f52, ...}, ...)
	/Users/duboisea/go/src/github.com/pion/mediadevices/track.go:222 +0x33d
github.com/pion/mediadevices.(*AudioTrack).Bind(0x900?, {{0xc00002ef30, 0x20}, {{0x49a2398, 0x0, 0x0}, {0xc00007ec60, 0x1, 0x1}}, 0x3b106f52, ...})
	/Users/duboisea/go/src/github.com/pion/mediadevices/track.go:480 +0xc5
github.com/pion/webrtc/v3.(*RTPSender).Send(0xc000188b80, {{{0x49a2398, 0x0, 0x0}, {0xc00007ec60, 0x1, 0x1}}, {0xc0002e2040, 0x1, 0x1}})
	/Users/duboisea/go/pkg/mod/github.com/pion/webrtc/v3@v3.1.43/rtpsender.go:305 +0x4d5
github.com/pion/webrtc/v3.(*PeerConnection).startRTPSenders(0x45bde80?, {0xc0002f2a30, 0x2, 0xc0001b2550?})
	/Users/duboisea/go/pkg/mod/github.com/pion/webrtc/v3@v3.1.43/peerconnection.go:1386 +0x1b8
github.com/pion/webrtc/v3.(*PeerConnection).SetLocalDescription(0xc0000c5440, {0x3, {0xc00018d500, 0x67f}, 0xc0002e4ea0})
	/Users/duboisea/go/pkg/mod/github.com/pion/webrtc/v3@v3.1.43/peerconnection.go:987 +0x37e
main.main()
	/Users/duboisea/go/src/github.com/pion/mediadevices/examples/webrtc/main.go:118 +0x649
exit status 2
```

I am looking into this now!

**Comment by Sean-Der** [comment]
Segfault appears in cd6aaa1393cbc623d8040c9f5fdd0604ec40f028
